const moods = [
  {
    id: 0,
    moodName_kr: '행복한',
    moodName: 'happy',
    color: 'aqua',
  },
  {
    id: 1,
    moodName_kr: '희망찬',
    moodName: 'hopeful',
    color: 'lightslategray',
  },
  {
    id: 2,
    moodName_kr: '사랑스러운',
    moodName: 'lovely',
    color: 'deepskyblue',
  },
  {
    id: 3,
    moodName_kr: '차분한',
    moodName: 'calm',
    color: 'lightpink',
  },
  {
    id: 4,
    moodName_kr: '낭만적인',
    moodName: 'romantic',
    color: 'salmon',
  },
  {
    id: 5,
    moodName_kr: '스트레스받는',
    moodName: 'stressful',
    color: 'purple',
  },
  {
    id: 6,
    moodName_kr: '화나는',
    moodName: 'angry',
    color: 'aquamarine',
  },
  {
    id: 7,
    moodName_kr: '상쾌한',
    moodName: 'fresh',
    color: 'lightsalmon',
  },
  {
    id: 8,
    moodName_kr: '우울한',
    moodName: 'blue',
    color: 'lemonchiffon',
  },
  {
    id: 9,
    moodName_kr: '설레는',
    moodName: 'flutter',
    color: 'aqua',
  },
  {
    id: 10,
    moodName_kr: '몽환적인',
    moodName: 'dreamy',
    color: 'lightslategray',
  },
  {
    id: 11,
    moodName_kr: '불안한',
    moodName: 'anxious',
    color: 'deepskyblue',
  },
  {
    id: 12,
    moodName_kr: '한가로운',
    moodName: 'relaxed',
    color: 'lightpink',
  },
  {
    id: 13,
    moodName_kr: '이별한',
    moodName: 'break up',
    color: 'salmon',
  },
  {
    id: 14,
    moodName_kr: '후회하는',
    moodName: 'regretful',
    color: 'purple',
  },
  {
    id: 15,
    moodName_kr: '그리운',
    moodName: 'nostalgic',
    color: 'aquamarine',
  },
  {
    id: 16,
    moodName_kr: '사랑하는',
    moodName: 'fall in love',
    color: 'lightsalmon',
  },
  {
    id: 17,
    moodName_kr: '외로운',
    moodName: 'lonely',
    color: 'lemonchiffon',
  },
  {
    id: 18,
    moodName_kr: '답답한',
    moodName: 'stuffy',
    color: 'aqua',
  },
  {
    id: 19,
    moodName_kr: '자신감있는',
    moodName: 'confident',
    color: 'lightslategray',
  },
  {
    id: 20,
    moodName_kr: '즐거운',
    moodName: 'joyful',
    color: 'deepskyblue',
  },
  {
    id: 21,
    moodName_kr: '달달한',
    moodName: 'sweety',
    color: 'lightpink',
  },
  {
    id: 22,
    moodName_kr: '화끈한',
    moodName: 'hot',
    color: 'salmon',
  },
  {
    id: 23,
    moodName_kr: '귀여운',
    moodName: 'cute',
    color: 'purple',
  },
  {
    id: 24,
    moodName_kr: '추억하는',
    moodName: 'memory',
    color: 'aquamarine',
  },
];

export default moods;
